
export const REQUEST_LOGIN             = 'REQUEST_LOGIN';
export const LOGIN                     = 'LOGIN';
export const LOGOUT                    = 'LOGOUT';
export const LOGIN_FAILURE             = 'LOGIN_FAILURE';
export const REQUEST_GET_USER_BY_TOKEN = 'REQUEST_GET_USER_BY_TOKEN';
export const GET_USER_BY_TOKEN_SUCCESS = 'GET_USER_BY_TOKEN_SUCCESS';
export const GET_USER_BY_TOKEN_FAILURE = 'GET_USER_BY_TOKEN_FAILURE';

export const GET_OBJECTS    = 'GET_OBJECTS';
export const GET_TOOLTIP    = 'GET_TOOLTIP';
// export const RESET_TOOLTIP  = 'RESET_TOOLTIP';

export const GET_LOCATIONS                     = 'GET_LOCATIONS';
export const CREATE_LOCATION_DETAILS           = 'CREATE_LOCATION_DETAILS';
export const ADD_OBJECT                        = 'ADD_OBJECT';
export const REQUEST_GET_OBJECT_ITEMS          = 'REQUEST_GET_OBJECT_ITEMS';
export const RECEIVE_GET_OBJECT_ITEMS_SUCCEESS = 'RECEIVE_GET_OBJECT_ITEMS_SUCCEESS';
export const RECEIVE_GET_OBJECT_ITEMS_ERROR    = 'RECEIVE_GET_OBJECT_ITEMS_ERROR';
export const UPDATE_OBJECT                     = 'UPDATE_OBJECT';
export const UPDATE_OBJECT_DETAILS             = 'UPDATE_OBJECT_DETAILS';
export const DELETE_OBJECT                     = 'DELETE_OBJECT';

export const ADD_LOCATION                   = 'ADD_LOCATION';
export const REQUEST_GET_LOCATIONS          = 'REQUEST_GET_LOCATIONS';
export const RECEIVE_GET_LOCATIONS_SUCCEESS = 'RECEIVE_GET_LOCATIONS_SUCCEESS';
export const RECEIVE_GET_LOCATIONS_ERROR    = 'RECEIVE_GET_LOCATIONS_ERROR';
export const UPDATE_LOCATION                = 'UPDATE_LOCATION'
export const UPDATE_LOCATION_DETAILS        = 'UPDATE_LOCATION_DETAILS';;
export const DELETE_LOCATION                = 'DELETE_LOCATION';
export const REQUEST_GET_LOCATIONS_NOT_IN_CONTRACT          = 'REQUEST_GET_LOCATIONS_NOT_IN_CONTRACT';
export const RECEIVE_GET_LOCATIONS_NOT_IN_CONTRACT_SUCCEESS = 'RECEIVE_GET_LOCATIONS_NOT_IN_CONTRACT_SUCCEESS';
export const RECEIVE_GET_LOCATIONS_NOT_IN_CONTRACT_ERROR    = 'RECEIVE_GET_LOCATIONS_NOT_IN_CONTRACT_ERROR';

export const UPDATE_FLOOR_NAME     = 'UPDATE_FLOOR_NAME';
export const UPDATE_FLOOR_BUILDING = 'UPDATE_FLOOR_BUILDING';

export const LOCK_FLOOR = 'LOCK_FLOOR';

export const ELEMENT_SELECTED = 'ELEMENT_SELECTED';

export const COSTCENTERS_BACKLIGHT_CHANGED = 'COSTCENTERS_BACKLIGHT_CHANGED';
export const PROJECTS_BACKLIGHT_CHANGED    = 'PROJECTS_BACKLIGHT_CHANGED';
export const SET_COSTCENTERS_TO_SHOW       = 'SET_COSTCENTERS_TO_SHOW';
export const SET_PROJECTS_TO_SHOW          = 'SET_PROJECTS_TO_SHOW';
export const SET_COSTCETNERS_BACKLIGHT     = 'SET_COSTCETNERS_BACKLIGHT';
export const SET_PROJECTS_BACKLIGHT        = 'SET_PROJECTS_BACKLIGHT';

export const UPDATE_PROFILE               = 'UPDATE_PROFILE';
export const REQUEST_GET_PROFILE          = 'REQUEST_GET_PROFILE';
export const RECEIVE_GET_PROFILE_SUCCEESS = 'RECEIVE_GET_PROFILE_SUCCEESS';
export const RECEIVE_GET_PROFILE_ERROR    = 'RECEIVE_GET_PROFILE_ERROR';

export const UPDATE_CITY = 'UPDATE_CITY';
export const ADD_CITY    = 'ADD_CITY';
export const REMOVE_CITY = 'REMOVE_CITY';
export const GET_CITIES  = 'GET_CITIES';
export const GET_CITY    = 'GET_CITY';

export const UPDATE_OFFICE = 'UPDATE_OFFICE';
export const ADD_OFFICE    = 'ADD_OFFICE';
export const REMOVE_OFFICE = 'REMOVE_OFFICE';
export const GET_OFFICES   = 'GET_OFFICES';
export const GET_OFFICE    = 'GET_OFFICE';

export const UPDATE_BUILDING = 'UPDATE_BUILDING';
export const ADD_BUILDING    = 'ADD_BUILDING';
export const REMOVE_BUILDING = 'REMOVE_BUILDING';
export const GET_BUILDINGS   = 'GET_BUILDINGS';
export const GET_BUILDING    = 'GET_BUILDING';

export const UPDATE_FLOOR = 'UPDATE_FLOOR';
export const ADD_FLOOR    = 'ADD_FLOOR';
export const REMOVE_FLOOR = 'REMOVE_FLOOR';
export const GET_FLOORS   = 'GET_FLOORS';
export const GET_FLOOR    = 'GET_FLOOR';
export const SAVE_FLOOR_TO_HISTORY   = 'SAVE_FLOOR_TO_HISTORY';
export const SET_FLOOR_FROM_HISTORY  = 'SET_FLOOR_FROM_HISTORY';
export const RESET_FLOOR_STATE  = 'RESET_FLOOR_STATE';
export const COPY_TO_BUFFER  = 'COPY_TO_BUFFER';
export const CLEAR_BUFFER  = 'CLEAR_BUFFER';
export const SHOW_LOCATION_NAMES = 'SHOW_LOCATION_NAMES';
export const SHOW_OBJECT_ITEMS = 'SHOW_OBJECT_ITEMS';
export const SHOW_DESK_TYPE = 'SHOW_DESK_TYPE';
export const SHOW_OBJECT_NAMES = 'SHOW_OBJECT_NAMES';
export const SHOW_DS_LIGHT = 'SHOW_DS_LIGHT';
export const MARK_DS_READY = 'MARK_DS_READY';
export const INVENTORY_MODE = 'INVENTORY_MODE';
export const SET_SIDEBAR_MARKUP_STATE = 'SET_SIDEBAR_MARKUP_STATE';

export const REQUEST_GET_FLOOR_DETAILS          = 'REQUEST_GET_FLOOR_DETAILS';
export const RECEIVE_GET_FLOOR_DETAILS_SUCCEESS = 'RECEIVE_GET_FLOOR_DETAILS_SUCCEESS';
export const RECEIVE_GET_FLOOR_DETAILS_ERROR    = 'RECEIVE_GET_FLOOR_DETAILS_ERROR';
export const INIT_FLOOR_DETAILS                 = 'INIT_FLOOR_DETAILS';
export const UPDATE_FLOOR_DETAILS               = 'UPDATE_FLOOR_DETAILS';
export const REMOVE_FLOOR_DETAILS               = 'REMOVE_FLOOR_DETAILS';
export const UPDATE_ONE_METAVALUE               = 'UPDATE_ONE_METAVALUE';

export const UPDATE_LOCATION_TYPE = 'UPDATE_LOCATION_TYPE';
export const ADD_LOCATION_TYPE    = 'ADD_LOCATION_TYPE';
export const REMOVE_LOCATION_TYPE = 'REMOVE_LOCATION_TYPE';
export const GET_LOCATION_TYPES   = 'GET_LOCATION_TYPES';
export const GET_LOCATION_TYPE    = 'GET_LOCATION_TYPE';

export const UPDATE_OBJECT_TYPE = 'UPDATE_OBJECT_TYPE';
export const ADD_OBJECT_TYPE    = 'ADD_OBJECT_TYPE';
export const REMOVE_OBJECT_TYPE = 'REMOVE_OBJECT_TYPE';
export const GET_OBJECT_TYPES   = 'GET_OBJECT_TYPES';
export const GET_OBJECT_TYPE    = 'GET_OBJECT_TYPE';

export const GET_OBJECT_ITEMS   = 'GET_OBJECT_ITEMS';
export const GET_OBJECT_ITEM    = 'GET_OBJECT_ITEM';
export const REMOVE_OBJECT_ITEM = 'REMOVE_OBJECT_ITEM';

export const UPDATE_META_TYPE = 'UPDATE_META_TYPE';
export const ADD_META_TYPE    = 'ADD_META_TYPE';
export const REMOVE_META_TYPE = 'REMOVE_META_TYPE';
export const GET_META_TYPES   = 'GET_META_TYPES';
export const GET_META_TYPE    = 'GET_META_TYPE';

export const UPDATE_META_FIELD = 'UPDATE_META_FIELD';
export const ADD_META_FIELD    = 'ADD_META_FIELD';
export const REMOVE_META_FIELD = 'REMOVE_META_FIELD';
export const GET_META_FIELDS   = 'GET_META_FIELDS';
export const GET_META_FIELD    = 'GET_META_FIELD';

export const UPDATE_META_MAP = 'UPDATE_META_MAP';
export const ADD_META_MAP    = 'ADD_META_MAP';
export const REMOVE_META_MAP = 'REMOVE_META_MAP';
export const GET_META_MAPS   = 'GET_META_MAPS';
export const GET_META_MAP    = 'GET_META_MAP';

export const GET_ATTRIBUTES            = 'GET_ATTRIBUTES';
export const UPDATE_ATTRIBUTES         = 'UPDATE_ATTRIBUTES';
export const UPDATE_CONTRACT_REFERENCE = 'UPDATE_CONTRACT_REFERENCE';
export const ADD_CONTRACT_REFERENCE    = 'ADD_CONTRACT_REFERENCE';
export const DELETE_CONTRACT_REFERENCE = 'DELETE_CONTRACT_REFERENCE';
export const REQUEST_GET_CONTRACTS     = 'REQUEST_GET_CONTRACTS';
export const REQUEST_GET_CONTRACT      = 'REQUEST_GET_CONTRACT';
export const RECEIVE_GET_CONTRACTS_SUCCESS = 'RECEIVE_GET_CONTRACTS_SUCCESS';
export const RECEIVE_GET_CONTRACTS_ERROR = "RECEIVE_GET_CONTRACTS_ERROR";
export const UPDATE_CONTRACT           = 'UPDATE_CONTRACT';
export const ADD_CONTRACT              = 'ADD_CONTRACT';
export const DELETE_CONTRACT           = 'DELETE_CONTRACT';
export const GET_EMPLOYEES             = 'GET_EMPLOYEES';
export const GET_EMPLOYEEBY_ID         = 'GET_EMPLOYEEBY_ID';
export const REMOVE_EMPLOYEE           = 'REMOVE_EMPLOYEE';

export const REQUEST_GET_ALL_EMPLOYEES         = 'REQUEST_GET_ALL_EMPLOYEES';
export const RECEIVE_GET_ALL_EMPLOYEES_SUCCESS = 'RECEIVE_GET_ALL_EMPLOYEES_SUCCESS';
export const RECEIVE_GET_ALL_EMPLOYEES_ERROR   = 'RECEIVE_GET_ALL_EMPLOYEES_ERROR';

export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';

export const REQUEST_SEARCH_EMPLOYEES_ON_PLACE              = 'REQUEST_SEARCH_EMPLOYEES_ON_PLACE';
export const RECEIVE_SEARCH_EMPLOYEES_ON_PLACE_SUCCESS      = 'RECEIVE_SEARCH_EMPLOYEES_ON_PLACE_SUCCESS';
export const RECEIVE_SEARCH_EMPLOYEES_ON_PLACE_ERROR        = 'RECEIVE_SEARCH_EMPLOYEES_ON_PLACE_ERROR';
export const REQUEST_SEARCH_EMPLOYEES_WITH_NO_PLACE         = 'REQUEST_SEARCH_EMPLOYEES_WITH_NO_PLACE';
export const RECEIVE_SEARCH_EMPLOYEES_WITH_NO_PLACE_SUCCESS = 'RECEIVE_SEARCH_EMPLOYEES_WITH_NO_PLACE_SUCCESS';
export const RECEIVE_SEARCH_EMPLOYEES_WITH_NO_PLACE_ERROR   = 'RECEIVE_SEARCH_EMPLOYEES_WITH_NO_PLACE_ERROR';
export const REQUEST_SEARCH_ROOMS_AND_LOCATIONS             = 'REQUEST_SEARCH_ROOMS_AND_LOCATIONS';
export const RECEIVE_SEARCH_ROOMS_AND_LOCATIONS_SUCCESS     = 'RECEIVE_SEARCH_ROOMS_AND_LOCATIONS_SUCCESS';
export const RECEIVE_SEARCH_ROOMS_AND_LOCATIONS_ERROR       = 'RECEIVE_SEARCH_ROOMS_AND_LOCATIONS_ERROR';
export const REQUEST_SEARCH_LOCATIONS_FOR_CONTRACTS         = 'REQUEST_SEARCH_LOCATIONS_FOR_CONTRACTS';
export const RECEIVE_SEARCH_LOCATIONS_FOR_CONTRACTS_SUCCESS = 'RECEIVE_SEARCH_LOCATIONS_FOR_CONTRACTS_SUCCESS';
export const RECEIVE_SEARCH_LOCATIONS_FOR_CONTRACTS_ERROR   = 'RECEIVE_SEARCH_LOCATIONS_FOR_CONTRACTS_ERROR';
export const REQUEST_SEARCH_OBJECTS_AND_DESKS               = 'REQUEST_SEARCH_OBJECTS_AND_DESKS';     
export const RECEIVE_SEARCH_OBJECTS_AND_DESKS_SUCCESS       = 'RECEIVE_SEARCH_OBJECTS_AND_DESKS_SUCCESS';    
export const RECEIVE_SEARCH_OBJECTS_AND_DESKS_ERROR         = 'RECEIVE_SEARCH_OBJECTS_AND_DESKS_ERROR';    

export const REQUEST_SEARCH_EMPLOYEES_FOR_GROUP         = 'REQUEST_SEARCH_EMPLOYEES_FOR_GROUP';
export const RECEIVE_SEARCH_EMPLOYEES_FOR_GROUP_SUCCESS = 'RECEIVE_SEARCH_EMPLOYEES_FOR_GROUP_SUCCESS';
export const RECEIVE_SEARCH_EMPLOYEES_FOR_GROUP_ERROR   = 'RECEIVE_SEARCH_EMPLOYEES_FOR_GROUP_ERROR';

export const REQUEST_SEARCH_BOOKINGS         = 'REQUEST_SEARCH_BOOKINGS';
export const RECEIVE_SEARCH_BOOKINGS_SUCCESS = 'RECEIVE_SEARCH_BOOKINGS_SUCCESS';
export const RECEIVE_SEARCH_BOOKINGS_ERROR   = 'RECEIVE_SEARCH_BOOKINGS_ERROR';

export const GET_SEARCH_STATS   = 'GET_SEARCH_STATS';
export const GET_SEARCH_RESULTS   = 'GET_SEARCH_RESULTS';

export const GET_DS_PLACES         = 'GET_DS_PLACES';
export const GET_OBJECT_ITEM_BY_ID = 'GET_OBJECT_ITEM_BY_ID';

export const SEARCH_LOCATIONS   = 'SEARCH_LOCATIONS';
export const GET_LOCATION_BY_ID = 'GET_LOCATION_BY_ID';

export const REQUEST_GET_COSTCENTERS         = 'REQUEST_GET_COSTCENTERS';
export const RECEIVE_GET_COSTCENTERS_SUCCESS = 'RECEIVE_GET_COSTCENTERS_SUCCESS';
export const RECEIVE_GET_COSTCENTERS_ERROR   = 'RECEIVE_GET_COSTCENTERS_ERROR';

export const REQUEST_GET_PROJECTS         = 'REQUEST_GET_PROJECTS';
export const RECEIVE_GET_PROJECTS_SUCCESS = 'RECEIVE_GET_PROJECTS_SUCCESS';
export const RECEIVE_GET_PROJECTS_ERROR   = 'RECEIVE_GET_PROJECTS_ERROR';
export const GET_ALL_PROJECTS             = 'GET_ALL_PROJECTS';

export const REQUEST_GET_HEARTBEATS         = 'REQUEST_GET_HEARTBEATS';
export const RECEIVE_GET_HEARTBEATS_SUCCESS = 'RECEIVE_GET_HEARTBEATS_SUCCESS';
export const RECEIVE_GET_HEARTBEATS_ERROR   = 'RECEIVE_GET_HEARTBEATS_ERROR';

export const UPDATE_GROUPRIGHT               = 'UPDATE_GROUPRIGHT';
export const ADD_GROUPRIGHT                  = 'ADD_GROUPRIGHT';
export const REMOVE_GROUPRIGHT               = 'REMOVE_GROUPRIGHT';
export const REQUEST_GET_GROUPRIGHTS         = 'REQUEST_GET_GROUPRIGHTS';
export const RECEIVE_GET_GROUPRIGHTS_SUCCESS = 'RECEIVE_GET_GROUPRIGHTS_SUCCESS';
export const RECEIVE_GET_GROUPRIGHTS_ERROR   = 'RECEIVE_GET_GROUPRIGHTS_ERROR';
export const ADD_GROUPRIGHTS                 = 'ADD_GROUPRIGHTS';
export const REMOVE_GROUPRIGHTS              = 'REMOVE_GROUPRIGHTS';

export const GET_RIGHTS   = 'GET_RIGHTS';

export const REMOVE_ROLE = 'REMOVE_ROLE';

export const UPDATE_GROUP               = 'UPDATE_GROUP';
export const ADD_GROUP                  = 'ADD_GROUP';
export const REMOVE_GROUP               = 'REMOVE_GROUP';
export const REQUEST_GET_GROUPS         = 'REQUEST_GET_GROUPS';
export const RECEIVE_GET_GROUPS_SUCCESS = 'RECEIVE_GET_GROUPS_SUCCESS';
export const RECEIVE_GET_GROUPS_ERROR   = 'RECEIVE_GET_GROUPS_ERROR';

export const REQUEST_UPDATE_BOOKING         = 'REQUEST_UPDATE_BOOKING';
export const RECEIVE_UPDATE_BOOKING_SUCCESS = 'RECEIVE_UPDATE_BOOKING_SUCCESS';
export const RECEIVE_UPDATE_BOOKING_ERROR   = 'RECEIVE_UPDATE_BOOKING_ERROR';
export const REQUEST_ADD_BOOKING          = 'REQUEST_ADD_BOOKING';
export const RECEIVE_ADD_BOOKING_SUCCESS  = 'RECEIVE_ADD_BOOKING_SUCCESS';
export const RECEIVE_ADD_BOOKING_ERROR    = 'RECEIVE_ADD_BOOKING_ERROR';
export const REMOVE_BOOKING               = 'REMOVE_BOOKING';
export const REQUEST_GET_PAGE_OF_BOOKINGS         = 'REQUEST_GET_PAGE_OF_BOOKINGS';
export const RECEIVE_GET_PAGE_OF_BOOKINGS_SUCCESS = 'RECEIVE_GET_PAGE_OF_BOOKINGS_SUCCESS';
export const RECEIVE_GET_PAGE_OF_BOOKINGS_ERROR   = 'RECEIVE_GET_PAGE_OF_BOOKINGS_ERROR';
export const REQUEST_GET_PAGE_OF_BOOKINGS_FOR_PLACE         = 'REQUEST_GET_PAGE_OF_BOOKINGS_FOR_PLACE';
export const RECEIVE_GET_PAGE_OF_BOOKINGS_FOR_PLACE_SUCCESS = 'RECEIVE_GET_PAGE_OF_BOOKINGS_FOR_PLACE_SUCCESS';
export const RECEIVE_GET_PAGE_OF_BOOKINGS_FOR_PLACE_ERROR   = 'RECEIVE_GET_PAGE_OF_BOOKINGS_FOR_PLACE_ERROR';

export const GET_ALL_COSTCENTERS                        = 'GET_ALL_COSTCENTERS';
export const ADD_SDMANAGERS_COSTCENTER                  = 'ADD_SDMANAGERS_COSTCENTER';
export const REQUEST_ADD_ALL_COSTCENTERS                = 'REQUEST_ADD_ALL_COSTCENTERS';
export const RECEIVE_ADD_ALL_COSTCENTERS_SUCCESS        = 'RECEIVE_ADD_ALL_COSTCENTERS_SUCCESS';
export const RECEIVE_ADD_ALL_COSTCENTERS_ERROR          = 'RECEIVE_ADD_ALL_COSTCENTERS_ERROR';
export const REMOVE_SDMANAGERS_COSTCENTER               = 'REMOVE_SDMANAGERS_COSTCENTER';
export const REQUEST_REMOVE_ALL_COSTCENTERS             = 'REQUEST_REMOVE_ALL_COSTCENTERS';
export const RECEIVE_REMOVE_ALL_COSTCENTERS_SUCCESS     = 'RECEIVE_REMOVE_ALL_COSTCENTERS_SUCCESS';
export const RECEIVE_REMOVE_ALL_COSTCENTERS_ERROR       = 'RECEIVE_REMOVE_ALL_COSTCENTERS_ERROR';
export const REQUEST_GET_SDMANAGERS_COSTCENTERS         = 'REQUEST_GET_SDMANAGERS_COSTCENTERS';
export const RECEIVE_GET_SDMANAGERS_COSTCENTERS_SUCCESS = 'RECEIVE_GET_SDMANAGERS_COSTCENTERS_SUCCESS';
export const RECEIVE_GET_SDMANAGERS_COSTCENTERS_ERROR   = 'RECEIVE_GET_SDMANAGERS_COSTCENTERS_ERROR';

export const REQUEST_GET_OBJECTS_LOCATION         = 'REQUEST_GET_OBJECTS_LOCATION';
export const RECEIVE_GET_OBJECTS_LOCATION_SUCCESS = 'RECEIVE_GET_OBJECTS_LOCATION_SUCCESS';
export const RECEIVE_GET_OBJECTS_LOCATION_ERROR   = 'RECEIVE_GET_OBJECTS_LOCATION_ERROR';
export const REQUEST_GET_LOCATIONS_INFO           = 'REQUEST_GET_LOCATIONS_INFO';
export const RECEIVE_GET_LOCATIONS_INFO_SUCCESS   = 'RECEIVE_GET_LOCATIONS_INFO_SUCCESS';
export const RECEIVE_GET_LOCATIONS_INFO_ERROR     = 'RECEIVE_GET_LOCATIONS_INFO_ERROR';
export const ADD_COSTCENTERS_LOCATIONS            = 'ADD_COSTCENTERS_LOCATIONS';
export const ADD_EMPLOYEES_LOCATIONS              = 'ADD_EMPLOYEES_LOCATIONS';
export const ADD_PROJECTS_LOCATIONS               = 'REMOVE_PROJECTS_LOCATIONS';
export const REMOVE_COSTCENTERS_LOCATIONS         = 'REMOVE_COSTCENTERS_LOCATIONS';
export const REMOVE_EMPLOYEES_LOCATIONS           = 'REMOVE_EMPLOYEES_LOCATIONS';
export const REMOVE_PROJECTS_LOCATIONS            = 'REMOVE_PROJECTS_LOCATIONS';

export const SEARCH_LOCATION    = 'SEARCH_LOCATION';

export const SET_SELECTED_CITY       = 'SET_SELECTED_CITY';
export const SET_SELECTED_OFFICE     = 'SET_SELECTED_OFFICE';
export const SET_SELECTED_BUILDING   = 'SET_SELECTED_BUILDING';
export const SET_SELECTED_FLOOR      = 'SET_SELECTED_FLOOR';
export const GET_SELECTIONS          = 'GET_SELECTIONS';
export const SET_ALL_SELECTIONS      = 'SET_ALL_SELECTIONS';
export const MISS_BUILDING_SELECTION = 'MISS_BUILDING_SELECTION';
export const SCD                     = 'SCD';

export const REQUEST_GET_EMPLOYEES_IN_COSTCENTERS         = 'REQUEST_GET_EMPLOYEES_IN_COSTCENTERS ';
export const RECEIVE_GET_EMPLOYEES_IN_COSTCENTERS_SUCCESS = 'RECEIVE_GET_EMPLOYEES_IN_COSTCENTERS_SUCCESS';
export const RECEIVE_GET_EMPLOYEES_IN_COSTCENTERS_ERROR   = 'RECEIVE_GET_EMPLOYEES_IN_COSTCENTERS_ERROR';
export const REQUEST_GET_EMPLOYEES_IN_PROJECT         = 'REQUEST_GET_EMPLOYEES_IN_PROJECT ';
export const RECEIVE_GET_EMPLOYEES_IN_PROJECT_SUCCESS = 'RECEIVE_GET_EMPLOYEES_IN_PROJECT_SUCCESS';
export const RECEIVE_GET_EMPLOYEES_IN_PROJECT_ERROR   = 'RECEIVE_GET_EMPLOYEES_IN_PROJECT_ERROR';

export const REQUEST_GET_NON_SEATED_EMPLOYYES_REPORT         = 'REQUEST_GET_NON_SEATED_EMPLOYYES_REPORT ';
export const RECEIVE_GET_NON_SEATED_EMPLOYYES_REPORT_SUCCESS = 'RECEIVE_GET_NON_SEATED_EMPLOYYES_REPORT_SUCCESS';
export const RECEIVE_GET_NON_SEATED_EMPLOYYES_REPORT_ERROR   = 'RECEIVE_GET_NON_SEATED_EMPLOYYES_REPORT_ERROR';

export const REQUEST_GET_RESERVATIONS_REPORT         = 'REQUEST_GET_RESERVATIONS_REPORT ';
export const RECEIVE_GET_RESERVATIONS_REPORT_SUCCESS = 'RECEIVE_GET_RESERVATIONS_REPORT_SUCCESS';
export const RECEIVE_GET_RESERVATIONS_REPORT_ERROR   = 'RECEIVE_GET_RESERVATIONS_REPORT_ERROR';

export const REQUEST_GET_COSTCENTER_PLACES_REPORT         = 'REQUEST_GET_COSTCENTER_PLACES_REPORT ';
export const RECEIVE_GET_COSTCENTER_PLACES_REPORT_SUCCESS = 'RECEIVE_GET_COSTCENTER_PLACES_REPORT_SUCCESS';
export const RECEIVE_GET_COSTCENTER_PLACES_REPORT_ERROR   = 'RECEIVE_GET_COSTCENTER_PLACES_REPORT_ERROR';

export const REQUEST_GET_METERAGE_REPORT         = 'REQUEST_GET_METERAGE_REPORT ';
export const RECEIVE_GET_METERAGE_REPORT_SUCCESS = 'RECEIVE_GET_METERAGE_REPORT_SUCCESS';
export const RECEIVE_GET_METERAGE_REPORT_ERROR   = 'RECEIVE_GET_METERAGE_REPORT_ERROR';

export const REQUEST_GET_RELOCATION_REPORT         = 'REQUEST_GET_RELOCATION_REPORT ';
export const RECEIVE_GET_RELOCATION_REPORT_SUCCESS = 'RECEIVE_GET_RELOCATION_REPORT_SUCCESS';
export const RECEIVE_GET_RELOCATION_REPORT_ERROR   = 'RECEIVE_GET_RELOCATION_REPORT_ERROR';

export const SEND_REPORT = 'SEND_REPORT';

export const REQUEST_GET_INVENTORY         = 'REQUEST_GET_INVENTORY ';
export const RECEIVE_GET_INVENTORY_SUCCESS = 'RECEIVE_GET_INVENTORY_SUCCESS';
export const RECEIVE_GET_INVENTORY_ERROR   = 'RECEIVE_GET_INVENTORY_ERROR';

export const REMOVE_AVAILABLE_DATES_FOR_PARKING                 = 'REMOVE_AVAILABLE_DATES_FOR_PARKING';
export const REQUEST_ADD_AVAILABLE_DATES_FOR_PARKING            = 'REQUEST_ADD_AVAILABLE_DATES_FOR_PARKING';
export const RECEIVE_ADD_AVAILABLE_DATES_FOR_PARKING_SUCCESS    = 'RECEIVE_ADD_AVAILABLE_DATES_FOR_PARKING_SUCCESS';
export const RECEIVE_ADD_AVAILABLE_DATES_FOR_PARKING_ERROR      = 'RECEIVE_ADD_AVAILABLE_DATES_FOR_PARKING_ERROR';
export const REQUEST_UPDATE_AVAILABLE_DATES_FOR_PARKING         = 'REQUEST_UPDATE_AVAILABLE_DATES_FOR_PARKING';
export const RECEIVE_UPDATE_AVAILABLE_DATES_FOR_PARKING_SUCCESS = 'RECEIVE_UPDATE_AVAILABLE_DATES_FOR_PARKING_SUCCESS';
export const RECEIVE_UPDATE_AVAILABLE_DATES_FOR_PARKING_ERROR   = 'RECEIVE_UPDATE_AVAILABLE_DATES_FOR_PARKING_ERROR';
export const REQUEST_GET_AVAILABLE_DATES_FOR_PARKING            = 'REQUEST_GET_AVAILABLE_DATES_FOR_PARKING';
export const RECEIVE_GET_AVAILABLE_DATES_FOR_PARKING_SUCCESS    = 'RECEIVE_GET_AVAILABLE_DATES_FOR_PARKING_SUCCESS';
export const RECEIVE_GET_AVAILABLE_DATES_FOR_PARKING_ERROR      = 'RECEIVE_GET_AVAILABLE_DATES_FOR_PARKING_ERROR';